name: mi primer github action

on: 
  push:
    branches: 
    - "main"

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: say hello
        run: |
          echo "hello world"
      - name: print data
        run: date
      - run: |
          ls -l